#try
#Si comentas esta linea el try no se ejecutara pero el excpet si haciendo que el codigo funcione aun asi falte algo
variable = "Correcto"

try:
    print(variable)

except:
    print("Hay un problema")
